### ISSUE TITLE
Generates invalid puzzles

### ISSUE THREAD

**Issue by bryc** [thegreyd/sudoku_9X9_gen#1]
99.9% of these generated results have no possible solution. Very rarely, it will generate one with multiple solutions (still invalid). Test with https://www.sudokuwiki.org/sudoku.htm.

If this is `wontfix`, you should indicate that it is broken and archive the repo.

# example (9's)
![image](https://user-images.githubusercontent.com/1408749/82104515-47881800-96e5-11ea-8351-d28f988582af.png)
# example (7's)
![image](https://user-images.githubusercontent.com/1408749/82104732-0d6b4600-96e6-11ea-8f39-e14b24dfaf07.png)

# example (9's)
![image](https://user-images.githubusercontent.com/1408749/82104569-6f777b80-96e5-11ea-8c53-3e03b61e0b4f.png)
# example (6's)
![image](https://user-images.githubusercontent.com/1408749/82104604-933ac180-96e5-11ea-8bba-8b07d7ccae5f.png)

**Comment by thegreyd** [comment]
Hello! thanks for that, I'll archive it
